<?php
/**
 * One-time legacy migration: renames the original Turkish schema to English.
 * Safe to run repeatedly: every rename is guarded by information_schema checks.
 * Runs BEFORE the regular migration commands so old installs upgrade cleanly.
 */
function legacy_localization(PDO $pdo): array {
    $done = [];
    $db = $pdo->query('SELECT DATABASE()')->fetchColumn();
    $tableExists = function (string $t) use ($pdo, $db): bool {
        $s = $pdo->prepare('SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=? AND table_name=?');
        $s->execute([$db, $t]);
        return (bool)$s->fetchColumn();
    };
    $columnExists = function (string $t, string $c) use ($pdo, $db): bool {
        $s = $pdo->prepare('SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=? AND table_name=? AND column_name=?');
        $s->execute([$db, $t, $c]);
        return (bool)$s->fetchColumn();
    };

    $tables = [
        ['akis_sablonlari', 'workflow_templates'],
        ['aktiviteler', 'activities'],
        ['arsiv', 'archive'],
        ['aylik_raporlar', 'monthly_reports'],
        ['belgeler', 'documents'],
        ['bildirimler', 'notifications'],
        ['calisan_havuzu', 'talent_pool'],
        ['donemler', 'periods'],
        ['dosyalar', 'clients'],
        ['dosya_notlari', 'client_notes'],
        ['dosya_uyeleri', 'client_members'],
        ['duyurular', 'announcements'],
        ['duyuru_okuyanlar', 'announcement_readers'],
        ['ekipmanlar', 'equipment'],
        ['ekipman_hareketleri', 'equipment_logs'],
        ['etkinlikler', 'events'],
        ['etkinlik_ekipmanlari', 'event_equipment'],
        ['etkinlik_katilimcilari', 'event_participants'],
        ['fikirler', 'ideas'],
        ['form_alanlari', 'form_fields'],
        ['form_sablonlari', 'form_templates'],
        ['giderler', 'expenses'],
        ['giris_denemeleri', 'login_attempts'],
        ['gorevler', 'tasks'],
        ['gorev_adimlari', 'task_steps'],
        ['gorev_atananlar', 'task_assignees'],
        ['gorev_izleyiciler', 'task_watchers'],
        ['gorev_kontrol', 'task_checklist'],
        ['gorev_yonetici_notlari', 'task_manager_notes'],
        ['icerikler', 'contents'],
        ['kanallar', 'channels'],
        ['kanal_uyeleri', 'channel_members'],
        ['kisisel_isler', 'personal_todos'],
        ['kisisel_linkler', 'personal_links'],
        ['kisisel_notlar', 'personal_notes'],
        ['mentorluk', 'mentorship'],
        ['mesajlar', 'messages'],
        ['musteri_dosyalari', 'customer_clients'],
        ['odemeler', 'payments'],
        ['onaylar', 'approvals'],
        ['projeler', 'projects'],
        ['proje_degerlendirme', 'project_review'],
        ['proje_ek_talepler', 'project_ek_requests'],
        ['proje_kontrol_listesi', 'project_checklist'],
        ['proje_sablonlari', 'project_templates'],
        ['proje_uyeleri', 'project_members'],
        ['puanlar', 'ratings'],
        ['randevular', 'appointments'],
        ['sablon_adimlari', 'template_steps'],
        ['sosyal_hesaplar', 'social_accounts'],
        ['sosyal_metrikler', 'social_metrics'],
        ['sozlesmeler', 'contracts'],
        ['talepler', 'requests'],
        ['talep_cevaplari', 'request_replies'],
        ['yorumlar', 'comments'],
        ['yorum_tepkiler', 'comment_box_reactions'],
        ['zaman_kayitlari', 'time_entries'],
    ];
    foreach ($tables as [$old, $new]) {
        if ($tableExists($old) && !$tableExists($new)) {
            try { $pdo->exec("RENAME TABLE `$old` TO `$new`"); $done[] = "table $old->$new"; } catch (PDOException $e) { $done[] = 'ERR ' . $e->getMessage(); }
        }
    }

    $columns = [
        ['workflow_templates', 'ad', 'name'],
        ['workflow_templates', 'aciklama', 'description'],
        ['activities', 'ref_tur', 'ref_type'],
        ['activities', 'aciklama', 'description'],
        ['archive', 'dosya_id', 'client_id'],
        ['archive', 'proje_id', 'project_id'],
        ['archive', 'gorev_id', 'task_id'],
        ['archive', 'ad', 'name'],
        ['archive', 'dosya_yolu', 'file_path'],
        ['archive', 'boyut', 'size'],
        ['archive', 'uzanti', 'extension'],
        ['archive', 'yukleyen_id', 'uploader_id'],
        ['monthly_reports', 'dosya_id', 'client_id'],
        ['monthly_reports', 'donem', 'period'],
        ['monthly_reports', 'ozet', 'summary'],
        ['monthly_reports', 'yapilanlar', 'work_done'],
        ['monthly_reports', 'metrikler', 'metrics'],
        ['monthly_reports', 'yazan_id', 'author_id'],
        ['monthly_reports', 'durum', 'status'],
        ['documents', 'tur', 'type'],
        ['documents', 'no', 'doc_no'],
        ['documents', 'dosya_id', 'client_id'],
        ['documents', 'baslik', 'title'],
        ['documents', 'kalemler', 'items'],
        ['documents', 'kdv_oran', 'vat_rate'],
        ['documents', 'durum', 'status'],
        ['documents', 'gecerlilik', 'valid_until'],
        ['documents', 'notlar', 'notes'],
        ['documents', 'olusturan_id', 'created_by'],
        ['notifications', 'baslik', 'title'],
        ['notifications', 'mesaj', 'message'],
        ['notifications', 'okundu', 'is_read'],
        ['talent_pool', 'ad', 'name'],
        ['talent_pool', 'yetkinlik', 'skill'],
        ['talent_pool', 'calisildi', 'worked_before'],
        ['talent_pool', 'iletisim', 'contact'],
        ['talent_pool', 'cv_arsiv_id', 'cv_archive_id'],
        ['talent_pool', 'notu', 'note'],
        ['talent_pool', 'ekleyen_id', 'added_by'],
        ['periods', 'proje_id', 'project_id'],
        ['periods', 'yil', 'year'],
        ['periods', 'ay', 'month'],
        ['periods', 'durum', 'status'],
        ['clients', 'ad', 'name'],
        ['clients', 'tur', 'type'],
        ['clients', 'renk', 'color'],
        ['clients', 'aciklama', 'description'],
        ['clients', 'iletisim_ad', 'contact_name'],
        ['clients', 'iletisim_eposta', 'contact_email'],
        ['clients', 'iletisim_tel', 'contact_phone'],
        ['clients', 'durum', 'status'],
        ['client_notes', 'dosya_id', 'client_id'],
        ['client_notes', 'baslik', 'title'],
        ['client_notes', 'metin', 'text'],
        ['client_notes', 'sira', 'sort_order'],
        ['client_notes', 'guncelleyen_id', 'updated_by'],
        ['client_notes', 'guncelleme', 'update'],
        ['client_members', 'dosya_id', 'client_id'],
        ['announcements', 'baslik', 'title'],
        ['announcements', 'metin', 'text'],
        ['announcements', 'onemli', 'is_important'],
        ['announcements', 'olusturan_id', 'created_by'],
        ['announcement_readers', 'duyuru_id', 'announcement_id'],
        ['equipment', 'kod', 'code'],
        ['equipment', 'ad', 'name'],
        ['equipment', 'kategori', 'category'],
        ['equipment', 'foto', 'photo'],
        ['equipment', 'durum', 'status'],
        ['equipment', 'zimmet_user_id', 'custody_user_id'],
        ['equipment', 'zimmet_etkinlik_id', 'custody_event_id'],
        ['equipment', 'ariza_notu', 'fault_note'],
        ['equipment', 'satin_alma', 'purchase_date'],
        ['equipment', 'fiyat', 'price'],
        ['equipment', 'sd_durum', 'sd_status'],
        ['equipment', 'sd_icerik', 'sd_content'],
        ['equipment', 'aciklama', 'description'],
        ['equipment_logs', 'ekipman_id', 'equipment_id'],
        ['equipment_logs', 'hedef_user_id', 'target_user_id'],
        ['equipment_logs', 'etkinlik_id', 'event_id'],
        ['equipment_logs', 'tur', 'type'],
        ['equipment_logs', 'aciklama', 'description'],
        ['events', 'dosya_id', 'client_id'],
        ['events', 'proje_id', 'project_id'],
        ['events', 'baslik', 'title'],
        ['events', 'tur', 'type'],
        ['events', 'baslangic', 'start'],
        ['events', 'bitis', 'end'],
        ['events', 'yer', 'place'],
        ['events', 'aciklama', 'description'],
        ['events', 'katilimcilar', 'participants'],
        ['events', 'hatirlatildi', 'is_reminded'],
        ['events', 'olusturan_id', 'created_by'],
        ['events', 'alinacaklar', 'shopping_list'],
        ['events', 'ihtiyac_listesi', 'needs_list'],
        ['event_equipment', 'etkinlik_id', 'event_id'],
        ['event_equipment', 'ekipman_id', 'equipment_id'],
        ['event_participants', 'etkinlik_id', 'event_id'],
        ['ideas', 'fikir', 'idea'],
        ['ideas', 'kurum', 'organization'],
        ['ideas', 'aciklama', 'description'],
        ['ideas', 'oneren_id', 'proposer_id'],
        ['ideas', 'durum', 'status'],
        ['form_fields', 'sablon_id', 'template_id'],
        ['form_fields', 'sira', 'sort_order'],
        ['form_fields', 'etiket', 'tag'],
        ['form_fields', 'tip', 'type'],
        ['form_fields', 'secenekler', 'options'],
        ['form_fields', 'zorunlu', 'is_required'],
        ['form_templates', 'ad', 'name'],
        ['form_templates', 'aciklama', 'description'],
        ['form_templates', 'aktif', 'is_active'],
        ['expenses', 'tur', 'type'],
        ['expenses', 'baslik', 'title'],
        ['expenses', 'tutar', 'amount'],
        ['expenses', 'tarih', 'date'],
        ['expenses', 'durum', 'status'],
        ['expenses', 'tekrar', 'repeat'],
        ['expenses', 'son_tekrar', 'last_repeat'],
        ['expenses', 'aciklama', 'description'],
        ['login_attempts', 'eposta', 'email'],
        ['login_attempts', 'basarili', 'is_success'],
        ['tasks', 'proje_id', 'project_id'],
        ['tasks', 'donem_id', 'period_id'],
        ['tasks', 'baslik', 'title'],
        ['tasks', 'aciklama', 'description'],
        ['tasks', 'atanan_id', 'assignee_id'],
        ['tasks', 'olusturan_id', 'created_by'],
        ['tasks', 'oncelik', 'priority'],
        ['tasks', 'durum', 'status'],
        ['tasks', 'son_tarih', 'due_date'],
        ['tasks', 'tamamlanma', 'completion'],
        ['tasks', 'sira', 'sort_order'],
        ['tasks', 'kilit_acik', 'lock_bypassed'],
        ['tasks', 'tekrar', 'repeat'],
        ['tasks', 'son_tekrar', 'last_repeat'],
        ['tasks', 'etiketler', 'tags'],
        ['tasks', 'tahmini_dakika', 'estimated_minutes'],
        ['tasks', 'baslangic_tarihi', 'start_date'],
        ['tasks', 'arsivlendi', 'is_archived'],
        ['tasks', 'icerik_id', 'content_id'],
        ['task_steps', 'gorev_id', 'task_id'],
        ['task_steps', 'sira', 'sort_order'],
        ['task_steps', 'ad', 'name'],
        ['task_steps', 'sorumlu_id', 'owner_id'],
        ['task_steps', 'durum', 'status'],
        ['task_steps', 'tamam_tarih', 'done_date'],
        ['task_assignees', 'gorev_id', 'task_id'],
        ['task_watchers', 'gorev_id', 'task_id'],
        ['task_checklist', 'gorev_id', 'task_id'],
        ['task_checklist', 'ad', 'name'],
        ['task_checklist', 'tamam', 'is_done'],
        ['task_checklist', 'sira', 'sort_order'],
        ['task_manager_notes', 'gorev_id', 'task_id'],
        ['task_manager_notes', 'notu', 'note'],
        ['contents', 'dosya_id', 'client_id'],
        ['contents', 'proje_id', 'project_id'],
        ['contents', 'baslik', 'title'],
        ['contents', 'aciklama', 'description'],
        ['contents', 'tarih', 'date'],
        ['contents', 'saat', 'time'],
        ['contents', 'durum', 'status'],
        ['contents', 'olusturan_id', 'created_by'],
        ['channels', 'ad', 'name'],
        ['channels', 'tur', 'type'],
        ['channels', 'proje_id', 'project_id'],
        ['channels', 'simge', 'icon'],
        ['channel_members', 'kanal_id', 'channel_id'],
        ['channel_members', 'son_okuma', 'last_read'],
        ['channel_members', 'arsiv', 'archive'],
        ['personal_todos', 'ad', 'name'],
        ['personal_todos', 'tamam', 'is_done'],
        ['personal_todos', 'sira', 'sort_order'],
        ['personal_links', 'ad', 'name'],
        ['personal_notes', 'baslik', 'title'],
        ['personal_notes', 'metin', 'text'],
        ['personal_notes', 'renk', 'color'],
        ['personal_notes', 'guncelleme', 'update'],
        ['mentorship', 'uye_id', 'member_id'],
        ['mentorship', 'alan', 'field'],
        ['mentorship', 'proje_id', 'project_id'],
        ['mentorship', 'saha', 'practice_arena'],
        ['mentorship', 'cikti', 'output'],
        ['mentorship', 'durum', 'status'],
        ['messages', 'kanal_id', 'channel_id'],
        ['messages', 'mesaj', 'message'],
        ['customer_clients', 'dosya_id', 'client_id'],
        ['payments', 'proje_id', 'project_id'],
        ['payments', 'tur', 'type'],
        ['payments', 'baslik', 'title'],
        ['payments', 'tutar', 'amount'],
        ['payments', 'tarih', 'date'],
        ['payments', 'durum', 'status'],
        ['payments', 'aciklama', 'description'],
        ['approvals', 'proje_id', 'project_id'],
        ['approvals', 'baslik', 'title'],
        ['approvals', 'aciklama', 'description'],
        ['approvals', 'arsiv_id', 'archive_id'],
        ['approvals', 'icerik_id', 'content_id'],
        ['approvals', 'gorev_id', 'task_id'],
        ['approvals', 'durum', 'status'],
        ['approvals', 'gonderen_id', 'sender_id'],
        ['approvals', 'cevap_notu', 'reply_note'],
        ['approvals', 'cevap_tarih', 'reply_date'],
        ['approvals', 'cevaplayan_id', 'responder_id'],
        ['projects', 'dosya_id', 'client_id'],
        ['projects', 'ad', 'name'],
        ['projects', 'tur', 'type'],
        ['projects', 'aciklama', 'description'],
        ['projects', 'durum', 'status'],
        ['projects', 'baslangic', 'start'],
        ['projects', 'bitis', 'end'],
        ['projects', 'sozlesme_tutari', 'contract_amount'],
        ['projects', 'butce', 'budget'],
        ['projects', 'revize_limit', 'revision_limit'],
        ['projects', 'devralma', 'handover'],
        ['projects', 'ekip_rolleri', 'team_roles'],
        ['project_review', 'proje_id', 'project_id'],
        ['project_review', 'tur', 'type'],
        ['project_review', 'icerik', 'content'],
        ['project_review', 'guncelleyen_id', 'updated_by'],
        ['project_ek_requests', 'proje_id', 'project_id'],
        ['project_ek_requests', 'baslik', 'title'],
        ['project_ek_requests', 'tutar', 'amount'],
        ['project_ek_requests', 'kapsam_disi', 'out_of_scope'],
        ['project_ek_requests', 'durum', 'status'],
        ['project_ek_requests', 'aciklama', 'description'],
        ['project_ek_requests', 'olusturan_id', 'created_by'],
        ['project_checklist', 'proje_id', 'project_id'],
        ['project_checklist', 'kalem', 'item'],
        ['project_checklist', 'kontrol_notu', 'check_note'],
        ['project_checklist', 'sorumlu_id', 'owner_id'],
        ['project_checklist', 'tamam', 'is_done'],
        ['project_checklist', 'teslim', 'is_delivered'],
        ['project_checklist', 'sira', 'sort_order'],
        ['project_templates', 'ad', 'name'],
        ['project_templates', 'aciklama', 'description'],
        ['project_templates', 'gorevler', 'tasks'],
        ['project_members', 'proje_id', 'project_id'],
        ['ratings', 'ref_tur', 'ref_type'],
        ['ratings', 'proje_id', 'project_id'],
        ['ratings', 'puan', 'rating'],
        ['ratings', 'yorum', 'comment_box'],
        ['appointments', 'musteri_id', 'customer_id'],
        ['appointments', 'dosya_id', 'client_id'],
        ['appointments', 'konu', 'topic'],
        ['appointments', 'tarih', 'date'],
        ['appointments', 'online_istek', 'online_request'],
        ['appointments', 'notlar', 'notes'],
        ['appointments', 'durum', 'status'],
        ['appointments', 'alternatif_tarih', 'alternative_date'],
        ['appointments', 'etkinlik_id', 'event_id'],
        ['appointments', 'cevap_notu', 'reply_note'],
        ['template_steps', 'sablon_id', 'template_id'],
        ['template_steps', 'sira', 'sort_order'],
        ['template_steps', 'ad', 'name'],
        ['settings', 'anahtar', 'setting_key'],
        ['settings', 'deger', 'setting_value'],
        ['social_accounts', 'dosya_id', 'client_id'],
        ['social_accounts', 'kullanici_adi', 'username'],
        ['social_metrics', 'hesap_id', 'account_id'],
        ['social_metrics', 'tarih', 'date'],
        ['social_metrics', 'takipci', 'followers'],
        ['social_metrics', 'gonderi', 'post'],
        ['social_metrics', 'etkilesim', 'engagement'],
        ['social_metrics', 'girilen_id', 'entered_by'],
        ['contracts', 'dosya_id', 'client_id'],
        ['contracts', 'baslik', 'title'],
        ['contracts', 'baslangic', 'start'],
        ['contracts', 'bitis', 'end'],
        ['contracts', 'tutar', 'amount'],
        ['contracts', 'arsiv_id', 'archive_id'],
        ['contracts', 'aciklama', 'description'],
        ['contracts', 'hatirlatildi', 'is_reminded'],
        ['requests', 'sablon_id', 'template_id'],
        ['requests', 'dosya_id', 'client_id'],
        ['requests', 'proje_id', 'project_id'],
        ['requests', 'gonderen_id', 'sender_id'],
        ['requests', 'baslik', 'title'],
        ['requests', 'durum', 'status'],
        ['requests', 'atanan_id', 'assignee_id'],
        ['requests', 'gorev_id', 'task_id'],
        ['request_replies', 'talep_id', 'request_id'],
        ['request_replies', 'alan_id', 'field_id'],
        ['request_replies', 'deger', 'setting_value'],
        ['users', 'ad', 'name'],
        ['users', 'eposta', 'email'],
        ['users', 'sifre', 'password'],
        ['users', 'rol', 'role'],
        ['users', 'unvan', 'job_title'],
        ['users', 'dosya_id', 'client_id'],
        ['users', 'tema', 'theme'],
        ['users', 'renk', 'color'],
        ['users', 'gorev_gorunum', 'task_view'],
        ['users', 'maas', 'salary'],
        ['users', 'haftalik_kapasite', 'weekly_capacity'],
        ['users', 'izinler', 'permissions'],
        ['users', 'bildirim_tercihleri', 'notification_preferences'],
        ['users', 'widgetler', 'widgets'],
        ['users', 'karalama', 'scratchpad'],
        ['users', 'gorulen_surum', 'seen_version'],
        ['users', 'aktif', 'is_active'],
        ['users', 'son_giris', 'last_login'],
        ['comments', 'ref_tur', 'ref_type'],
        ['comments', 'mesaj', 'message'],
        ['comments', 'arsiv_id', 'archive_id'],
        ['comments', 'duzenlendi', 'is_edited'],
        ['comment_box_reactions', 'yorum_id', 'comment_box_id'],
        ['time_entries', 'gorev_id', 'task_id'],
        ['time_entries', 'dakika', 'minutes'],
        ['time_entries', 'tarih', 'date'],
        ['time_entries', 'aciklama', 'description'],
    ];
    foreach ($columns as [$tbl, $old, $new]) {
        if ($tableExists($tbl) && $columnExists($tbl, $old) && !$columnExists($tbl, $new)) {
            try { $pdo->exec("ALTER TABLE `$tbl` RENAME COLUMN `$old` TO `$new`"); $done[] = "col $tbl.$old->$new"; } catch (PDOException $e) { $done[] = 'ERR ' . $e->getMessage(); }
        }
    }
    return $done;
}
