<?php
/**
 * One-time legacy migration: renames the original Turkish schema to English.
 * Safe to run repeatedly: every rename is guarded by information_schema checks.
 * Runs BEFORE the regular migration commands so old installs upgrade cleanly.
 */
function legacy_localization(PDO $pdo): array {
    $done = [];
    $db = $pdo->query('SELECT DATABASE()')->fetchColumn();
    $tableExists = function (string $t) use ($pdo, $db): bool {
        $s = $pdo->prepare('SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=? AND table_name=?');
        $s->execute([$db, $t]);
        return (bool)$s->fetchColumn();
    };
    $columnExists = function (string $t, string $c) use ($pdo, $db): bool {
        $s = $pdo->prepare('SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=? AND table_name=? AND column_name=?');
        $s->execute([$db, $t, $c]);
        return (bool)$s->fetchColumn();
    };

    $tables = [
        ['workflow_templates', 'workflow_templates'],
        ['activities', 'activities'],
        ['archive', 'archive'],
        ['monthly_reports', 'monthly_reports'],
        ['documents', 'documents'],
        ['notifications', 'notifications'],
        ['talent_pool', 'talent_pool'],
        ['periods', 'periods'],
        ['clients', 'clients'],
        ['client_notes', 'client_notes'],
        ['client_members', 'client_members'],
        ['announcements', 'announcements'],
        ['announcement_readers', 'announcement_readers'],
        ['equipment', 'equipment'],
        ['equipment_logs', 'equipment_logs'],
        ['events', 'events'],
        ['event_equipment', 'event_equipment'],
        ['event_participants', 'event_participants'],
        ['ideas', 'ideas'],
        ['form_fields', 'form_fields'],
        ['form_templates', 'form_templates'],
        ['expenses', 'expenses'],
        ['login_attempts', 'login_attempts'],
        ['tasks', 'tasks'],
        ['task_steps', 'task_steps'],
        ['task_assignees', 'task_assignees'],
        ['task_watchers', 'task_watchers'],
        ['task_checklist', 'task_checklist'],
        ['task_manager_notes', 'task_manager_notes'],
        ['contents', 'contents'],
        ['channels', 'channels'],
        ['channel_members', 'channel_members'],
        ['personal_todos', 'personal_todos'],
        ['personal_links', 'personal_links'],
        ['personal_notes', 'personal_notes'],
        ['mentorship', 'mentorship'],
        ['messages', 'messages'],
        ['customer_clients', 'customer_clients'],
        ['payments', 'payments'],
        ['approvals', 'approvals'],
        ['projects', 'projects'],
        ['project_review', 'project_review'],
        ['project_ek_requests', 'project_ek_requests'],
        ['project_checklist', 'project_checklist'],
        ['project_templates', 'project_templates'],
        ['project_members', 'project_members'],
        ['ratings', 'ratings'],
        ['appointments', 'appointments'],
        ['template_steps', 'template_steps'],
        ['social_accounts', 'social_accounts'],
        ['social_metrics', 'social_metrics'],
        ['contracts', 'contracts'],
        ['requests', 'requests'],
        ['request_replies', 'request_replies'],
        ['comments', 'comments'],
        ['comment_box_reactions', 'comment_box_reactions'],
        ['time_entries', 'time_entries'],
    ];
    foreach ($tables as [$old, $new]) {
        if ($tableExists($old) && !$tableExists($new)) {
            try { $pdo->exec("RENAME TABLE `$old` TO `$new`"); $done[] = "table $old->$new"; } catch (PDOException $e) { $done[] = 'ERR ' . $e->getMessage(); }
        }
    }

    $columns = [
        ['workflow_templates', 'name', 'name'],
        ['workflow_templates', 'description', 'description'],
        ['activities', 'ref_type', 'ref_type'],
        ['activities', 'description', 'description'],
        ['archive', 'client_id', 'client_id'],
        ['archive', 'project_id', 'project_id'],
        ['archive', 'task_id', 'task_id'],
        ['archive', 'name', 'name'],
        ['archive', 'file_path', 'file_path'],
        ['archive', 'size', 'size'],
        ['archive', 'extension', 'extension'],
        ['archive', 'uploader_id', 'uploader_id'],
        ['monthly_reports', 'client_id', 'client_id'],
        ['monthly_reports', 'period', 'period'],
        ['monthly_reports', 'summary', 'summary'],
        ['monthly_reports', 'work_done', 'work_done'],
        ['monthly_reports', 'metrics', 'metrics'],
        ['monthly_reports', 'author_id', 'author_id'],
        ['monthly_reports', 'status', 'status'],
        ['documents', 'type', 'type'],
        ['documents', 'doc_no', 'doc_no'],
        ['documents', 'client_id', 'client_id'],
        ['documents', 'title', 'title'],
        ['documents', 'items', 'items'],
        ['documents', 'vat_rate', 'vat_rate'],
        ['documents', 'status', 'status'],
        ['documents', 'valid_until', 'valid_until'],
        ['documents', 'notes', 'notes'],
        ['documents', 'created_by', 'created_by'],
        ['notifications', 'title', 'title'],
        ['notifications', 'message', 'message'],
        ['notifications', 'is_read', 'is_read'],
        ['talent_pool', 'name', 'name'],
        ['talent_pool', 'skill', 'skill'],
        ['talent_pool', 'worked_before', 'worked_before'],
        ['talent_pool', 'contact', 'contact'],
        ['talent_pool', 'cv_archive_id', 'cv_archive_id'],
        ['talent_pool', 'note', 'note'],
        ['talent_pool', 'added_by', 'added_by'],
        ['periods', 'project_id', 'project_id'],
        ['periods', 'year', 'year'],
        ['periods', 'month', 'month'],
        ['periods', 'status', 'status'],
        ['clients', 'name', 'name'],
        ['clients', 'type', 'type'],
        ['clients', 'color', 'color'],
        ['clients', 'description', 'description'],
        ['clients', 'contact_name', 'contact_name'],
        ['clients', 'contact_email', 'contact_email'],
        ['clients', 'contact_phone', 'contact_phone'],
        ['clients', 'status', 'status'],
        ['client_notes', 'client_id', 'client_id'],
        ['client_notes', 'title', 'title'],
        ['client_notes', 'metin', 'text'],
        ['client_notes', 'sort_order', 'sort_order'],
        ['client_notes', 'updated_by', 'updated_by'],
        ['client_notes', 'update', 'update'],
        ['client_members', 'client_id', 'client_id'],
        ['announcements', 'title', 'title'],
        ['announcements', 'metin', 'text'],
        ['announcements', 'is_important', 'is_important'],
        ['announcements', 'created_by', 'created_by'],
        ['announcement_readers', 'announcement_id', 'announcement_id'],
        ['equipment', 'code', 'code'],
        ['equipment', 'name', 'name'],
        ['equipment', 'category', 'category'],
        ['equipment', 'photo', 'photo'],
        ['equipment', 'status', 'status'],
        ['equipment', 'custody_user_id', 'custody_user_id'],
        ['equipment', 'custody_event_id', 'custody_event_id'],
        ['equipment', 'fault_note', 'fault_note'],
        ['equipment', 'purchase_date', 'purchase_date'],
        ['equipment', 'price', 'price'],
        ['equipment', 'sd_status', 'sd_status'],
        ['equipment', 'sd_content', 'sd_content'],
        ['equipment', 'description', 'description'],
        ['equipment_logs', 'equipment_id', 'equipment_id'],
        ['equipment_logs', 'target_user_id', 'target_user_id'],
        ['equipment_logs', 'event_id', 'event_id'],
        ['equipment_logs', 'type', 'type'],
        ['equipment_logs', 'description', 'description'],
        ['events', 'client_id', 'client_id'],
        ['events', 'project_id', 'project_id'],
        ['events', 'title', 'title'],
        ['events', 'type', 'type'],
        ['events', 'start', 'start'],
        ['events', 'end', 'end'],
        ['events', 'place', 'place'],
        ['events', 'description', 'description'],
        ['events', 'participants', 'participants'],
        ['events', 'is_reminded', 'is_reminded'],
        ['events', 'created_by', 'created_by'],
        ['events', 'shopping_list', 'shopping_list'],
        ['events', 'needs_list', 'needs_list'],
        ['event_equipment', 'event_id', 'event_id'],
        ['event_equipment', 'equipment_id', 'equipment_id'],
        ['event_participants', 'event_id', 'event_id'],
        ['ideas', 'fikir', 'idea'],
        ['ideas', 'organization', 'organization'],
        ['ideas', 'description', 'description'],
        ['ideas', 'proposer_id', 'proposer_id'],
        ['ideas', 'status', 'status'],
        ['form_fields', 'template_id', 'template_id'],
        ['form_fields', 'sort_order', 'sort_order'],
        ['form_fields', 'tag', 'tag'],
        ['form_fields', 'type', 'type'],
        ['form_fields', 'options', 'options'],
        ['form_fields', 'zorunlu', 'is_required'],
        ['form_templates', 'name', 'name'],
        ['form_templates', 'description', 'description'],
        ['form_templates', 'aktif', 'is_active'],
        ['expenses', 'type', 'type'],
        ['expenses', 'title', 'title'],
        ['expenses', 'amount', 'amount'],
        ['expenses', 'tarih', 'date'],
        ['expenses', 'status', 'status'],
        ['expenses', 'repeat', 'repeat'],
        ['expenses', 'last_repeat', 'last_repeat'],
        ['expenses', 'description', 'description'],
        ['login_attempts', 'eposta', 'email'],
        ['login_attempts', 'is_success', 'is_success'],
        ['tasks', 'project_id', 'project_id'],
        ['tasks', 'period_id', 'period_id'],
        ['tasks', 'title', 'title'],
        ['tasks', 'description', 'description'],
        ['tasks', 'assignee_id', 'assignee_id'],
        ['tasks', 'created_by', 'created_by'],
        ['tasks', 'priority', 'priority'],
        ['tasks', 'status', 'status'],
        ['tasks', 'due_date', 'due_date'],
        ['tasks', 'completion', 'completion'],
        ['tasks', 'sort_order', 'sort_order'],
        ['tasks', 'lock_bypassed', 'lock_bypassed'],
        ['tasks', 'repeat', 'repeat'],
        ['tasks', 'last_repeat', 'last_repeat'],
        ['tasks', 'tags', 'tags'],
        ['tasks', 'estimated_minutes', 'estimated_minutes'],
        ['tasks', 'start_date', 'start_date'],
        ['tasks', 'is_archived', 'is_archived'],
        ['tasks', 'content_id', 'content_id'],
        ['task_steps', 'task_id', 'task_id'],
        ['task_steps', 'sort_order', 'sort_order'],
        ['task_steps', 'name', 'name'],
        ['task_steps', 'owner_id', 'owner_id'],
        ['task_steps', 'status', 'status'],
        ['task_steps', 'done_date', 'done_date'],
        ['task_assignees', 'task_id', 'task_id'],
        ['task_watchers', 'task_id', 'task_id'],
        ['task_checklist', 'task_id', 'task_id'],
        ['task_checklist', 'name', 'name'],
        ['task_checklist', 'tamam', 'is_done'],
        ['task_checklist', 'sort_order', 'sort_order'],
        ['task_manager_notes', 'task_id', 'task_id'],
        ['task_manager_notes', 'note', 'note'],
        ['contents', 'client_id', 'client_id'],
        ['contents', 'project_id', 'project_id'],
        ['contents', 'title', 'title'],
        ['contents', 'description', 'description'],
        ['contents', 'tarih', 'date'],
        ['contents', 'time', 'time'],
        ['contents', 'status', 'status'],
        ['contents', 'created_by', 'created_by'],
        ['channels', 'name', 'name'],
        ['channels', 'type', 'type'],
        ['channels', 'project_id', 'project_id'],
        ['channels', 'icon', 'icon'],
        ['channel_members', 'channel_id', 'channel_id'],
        ['channel_members', 'last_read', 'last_read'],
        ['channel_members', 'archive', 'archive'],
        ['personal_todos', 'name', 'name'],
        ['personal_todos', 'tamam', 'is_done'],
        ['personal_todos', 'sort_order', 'sort_order'],
        ['personal_links', 'name', 'name'],
        ['personal_notes', 'title', 'title'],
        ['personal_notes', 'metin', 'text'],
        ['personal_notes', 'color', 'color'],
        ['personal_notes', 'update', 'update'],
        ['mentorship', 'member_id', 'member_id'],
        ['mentorship', 'field', 'field'],
        ['mentorship', 'project_id', 'project_id'],
        ['mentorship', 'practice_arena', 'practice_arena'],
        ['mentorship', 'output', 'output'],
        ['mentorship', 'status', 'status'],
        ['messages', 'channel_id', 'channel_id'],
        ['messages', 'message', 'message'],
        ['customer_clients', 'client_id', 'client_id'],
        ['payments', 'project_id', 'project_id'],
        ['payments', 'type', 'type'],
        ['payments', 'title', 'title'],
        ['payments', 'amount', 'amount'],
        ['payments', 'tarih', 'date'],
        ['payments', 'status', 'status'],
        ['payments', 'description', 'description'],
        ['approvals', 'project_id', 'project_id'],
        ['approvals', 'title', 'title'],
        ['approvals', 'description', 'description'],
        ['approvals', 'archive_id', 'archive_id'],
        ['approvals', 'content_id', 'content_id'],
        ['approvals', 'task_id', 'task_id'],
        ['approvals', 'status', 'status'],
        ['approvals', 'sender_id', 'sender_id'],
        ['approvals', 'reply_note', 'reply_note'],
        ['approvals', 'reply_date', 'reply_date'],
        ['approvals', 'responder_id', 'responder_id'],
        ['projects', 'client_id', 'client_id'],
        ['projects', 'name', 'name'],
        ['projects', 'type', 'type'],
        ['projects', 'description', 'description'],
        ['projects', 'status', 'status'],
        ['projects', 'start', 'start'],
        ['projects', 'end', 'end'],
        ['projects', 'contract_amount', 'contract_amount'],
        ['projects', 'budget', 'budget'],
        ['projects', 'revision_limit', 'revision_limit'],
        ['projects', 'handover', 'handover'],
        ['projects', 'team_roles', 'team_roles'],
        ['project_review', 'project_id', 'project_id'],
        ['project_review', 'type', 'type'],
        ['project_review', 'content', 'content'],
        ['project_review', 'updated_by', 'updated_by'],
        ['project_ek_requests', 'project_id', 'project_id'],
        ['project_ek_requests', 'title', 'title'],
        ['project_ek_requests', 'amount', 'amount'],
        ['project_ek_requests', 'out_of_scope', 'out_of_scope'],
        ['project_ek_requests', 'status', 'status'],
        ['project_ek_requests', 'description', 'description'],
        ['project_ek_requests', 'created_by', 'created_by'],
        ['project_checklist', 'project_id', 'project_id'],
        ['project_checklist', 'item', 'item'],
        ['project_checklist', 'check_note', 'check_note'],
        ['project_checklist', 'owner_id', 'owner_id'],
        ['project_checklist', 'tamam', 'is_done'],
        ['project_checklist', 'teslim', 'is_delivered'],
        ['project_checklist', 'sort_order', 'sort_order'],
        ['project_templates', 'name', 'name'],
        ['project_templates', 'description', 'description'],
        ['project_templates', 'tasks', 'tasks'],
        ['project_members', 'project_id', 'project_id'],
        ['ratings', 'ref_type', 'ref_type'],
        ['ratings', 'project_id', 'project_id'],
        ['ratings', 'rating', 'rating'],
        ['ratings', 'comment_box', 'comment_box'],
        ['appointments', 'customer_id', 'customer_id'],
        ['appointments', 'client_id', 'client_id'],
        ['appointments', 'topic', 'topic'],
        ['appointments', 'tarih', 'date'],
        ['appointments', 'online_request', 'online_request'],
        ['appointments', 'notes', 'notes'],
        ['appointments', 'status', 'status'],
        ['appointments', 'alternative_date', 'alternative_date'],
        ['appointments', 'event_id', 'event_id'],
        ['appointments', 'reply_note', 'reply_note'],
        ['template_steps', 'template_id', 'template_id'],
        ['template_steps', 'sort_order', 'sort_order'],
        ['template_steps', 'name', 'name'],
        ['settings', 'anahtar', 'setting_key'],
        ['settings', 'setting_value', 'setting_value'],
        ['social_accounts', 'client_id', 'client_id'],
        ['social_accounts', 'username', 'username'],
        ['social_metrics', 'account_id', 'account_id'],
        ['social_metrics', 'tarih', 'date'],
        ['social_metrics', 'followers', 'followers'],
        ['social_metrics', 'post', 'post'],
        ['social_metrics', 'engagement', 'engagement'],
        ['social_metrics', 'entered_by', 'entered_by'],
        ['contracts', 'client_id', 'client_id'],
        ['contracts', 'title', 'title'],
        ['contracts', 'start', 'start'],
        ['contracts', 'end', 'end'],
        ['contracts', 'amount', 'amount'],
        ['contracts', 'archive_id', 'archive_id'],
        ['contracts', 'description', 'description'],
        ['contracts', 'is_reminded', 'is_reminded'],
        ['requests', 'template_id', 'template_id'],
        ['requests', 'client_id', 'client_id'],
        ['requests', 'project_id', 'project_id'],
        ['requests', 'sender_id', 'sender_id'],
        ['requests', 'title', 'title'],
        ['requests', 'status', 'status'],
        ['requests', 'assignee_id', 'assignee_id'],
        ['requests', 'task_id', 'task_id'],
        ['request_replies', 'request_id', 'request_id'],
        ['request_replies', 'field_id', 'field_id'],
        ['request_replies', 'setting_value', 'setting_value'],
        ['users', 'name', 'name'],
        ['users', 'eposta', 'email'],
        ['users', 'password', 'password'],
        ['users', 'role', 'role'],
        ['users', 'job_title', 'job_title'],
        ['users', 'client_id', 'client_id'],
        ['users', 'theme', 'theme'],
        ['users', 'color', 'color'],
        ['users', 'task_view', 'task_view'],
        ['users', 'maas', 'salary'],
        ['users', 'weekly_capacity', 'weekly_capacity'],
        ['users', 'permissions', 'permissions'],
        ['users', 'notification_preferences', 'notification_preferences'],
        ['users', 'widgets', 'widgets'],
        ['users', 'scratchpad', 'scratchpad'],
        ['users', 'seen_version', 'seen_version'],
        ['users', 'aktif', 'is_active'],
        ['users', 'last_login', 'last_login'],
        ['comments', 'ref_type', 'ref_type'],
        ['comments', 'message', 'message'],
        ['comments', 'archive_id', 'archive_id'],
        ['comments', 'is_edited', 'is_edited'],
        ['comment_box_reactions', 'comment_box_id', 'comment_box_id'],
        ['time_entries', 'task_id', 'task_id'],
        ['time_entries', 'minutes', 'minutes'],
        ['time_entries', 'tarih', 'date'],
        ['time_entries', 'description', 'description'],
    ];
    foreach ($columns as [$tbl, $old, $new]) {
        if ($tableExists($tbl) && $columnExists($tbl, $old) && !$columnExists($tbl, $new)) {
            try { $pdo->exec("ALTER TABLE `$tbl` RENAME COLUMN `$old` TO `$new`"); $done[] = "col $tbl.$old->$new"; } catch (PDOException $e) { $done[] = 'ERR ' . $e->getMessage(); }
        }
    }
    return $done;
}
